### PR TITLE
update spec status

### PR DESCRIPTION
**Pull request by siusin**
Refs:

- WebApps Deliverables: https://www.w3.org/groups/wg/webapps/deliverables
- WebApps Charter:  https://www.w3.org/groups/wg/webapps/charters
- Old WebApps: https://www.w3.org/groups/wg/webapps-old/charters
- WebPlat: https://www.w3.org/groups/wg/webplatform/charters

### CODE REVIEW

**Review by dontcallmedom — APPROVED** [review]

**Comment by siusin** [comment]
A more detailed plan to move to CR/REC:

- File API: CR - Q2 2022; REC - Q3 2023;
- Gamepad: CR - Q1 2022; REC - Q2 2023;
- Image Resource: CR - Q3 2022; REC - Q3 2023;
- IndexedDB 3.0: CR - Q3 2022; REC - Q3 2023;
- Intersection Observer: CR - Q1 2022; REC - Q1 2023;
- Pointer Lock 2.0: CR - Q3 2022; REC - Q3 2023;
- Push API: CR - Q1 2022; REC - Q4 2022;
- Screen Orientation: CR - Q1 2022; REC - Q4 2022;
- Web App Manifest: CR - Q1 2022; REC - Q3 2022;
- ARIA in HTML: REC - Q1 2022;
- UI Events: CR - Q3 2022; REC - Q3 2023;
- UI Events KeyboardEvent code Values: REC - Q3 2022;
- UI Events KeyboardEvent key Values: REC - Q3 2022;
- Web Share: CR - Q1 2022; REC - Q3 2022;
- Web App Manifest - AppInfo:  CR - Q3 2022; REC - Q3 2023.

@marcoscaceres @LJWatson @dontcallmedom @vivienlacourba -- does it make sense to you?

**Comment by vivienlacourba** [comment]
> A more detailed plan to move to CR/REC:
> 
>     * File API: CR - Q2 2022; REC - Q3 2023;
> 
>     * Gamepad: CR - Q1 2022; REC - Q2 2023;
> 
>     * Image Resource: CR - Q3 2022; REC - Q3 2023;
> 
>     * IndexedDB 3.0: CR - Q3 2022; REC - Q3 2023;
> 
>     * Intersection Observer: CR - Q1 2022; REC - Q1 2023;
> 
>     * Pointer Lock 2.0: CR - Q3 2022; REC - Q3 2023;
> 
>     * Push API: CR - Q1 2022; REC - Q4 2022;
> 
>     * Screen Orientation: CR - Q1 2022; REC - Q4 2022;
> 
>     * Web App Manifest: CR - Q1 2022; REC - Q3 2022;
> 
>     * ARIA in HTML: REC - Q1 2022;
> 
>     * UI Events: CR - Q3 2022; REC - Q3 2023;
> 
>     * UI Events KeyboardEvent code Values: REC - Q3 2022;
> 
>     * UI Events KeyboardEvent key Values: REC - Q3 2022;
> 
>     * Web Share: CR - Q1 2022; REC - Q3 2022;
> 
>     * Web App Manifest - AppInfo:  CR - Q3 2022; REC - Q3 2023.
> 
> 
> @marcoscaceres @LJWatson @dontcallmedom @vivienlacourba -- does it make sense to you?

Those REC ETA periods do not (yet?) match the content of this PR, I guess your plan is to update this PR once you'll get approval on those new dates?
Otherwise LGTM.

**Comment by marcoscaceres** [comment]
@siusin, the proposed dates seem reasonable to me.

**Comment by siusin** [comment]
> Those REC ETA periods do not (yet?) match the content of this PR, I guess your plan is to update this PR once you'll get approval on those new dates?

Yes! see 6876795.

It should be ready now. Shall we merge it? @marcoscaceres

**Pull request merged**
